version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Le Dockerfile pour le service PHP avec Laravel
    container_name: app
    volumes:
      - .:/var/www  # Monter le projet dans le conteneur
      - ./gestion-ecole/issa.json://home/issa/Bureau/Laravel/GestionEcole/gestion-ecole/issa.json  # Monture du fichier JSON
    networks:
      - laravel
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres  # Nom du service PostgreSQL
      DB_PORT: 5432
      DB_DATABASE: laravelwalo
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "9000:9000"  # Exposer le port 9000 pour le serveur Laravel

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: laravelwalo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume persistant pour les données PostgreSQL
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:
